steps:
  # ----------------------------------------------------
  # 단계 1: Git 저장소와 모든 Submodule을 함께 클론합니다.
  # ----------------------------------------------------
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--recursive', 'https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.git', '.']
  # 'YOUR_USERNAME/YOUR_REPOSITORY.git' 부분을 실제 GitHub 저장소 주소로 바꾸세요.

  # ------------------------------------------------------------------
  # 단계 2: Docker 이미지를 빌드합니다.
  # 이 단계가 시작될 때, 작업 공간에는 chess-library 폴더가 이미 존재합니다.
  # ------------------------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/pgn-processing-repo/chesspgnparser', '.']
  # asia-northeast3-docker.pkg.dev/... 부분은 Artifact Registry 경로에 맞게 수정하세요.

# ---------------------------------------------
# 빌드가 완료된 이미지를 Artifact Registry에 푸시(업로드)합니다.
# ---------------------------------------------
images:
- 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/pgn-processing-repo/chesspgnparser'